### ISSUE TITLE
FR: 使用 css 替换移除元素

### ISSUE THREAD

**Issue by Cologler** [hanFengSan/TiebaCleaner#3]
使用 CSS 来隐藏元素而不是直接从页面上 remove 掉元素。

比如，统一给需要被移除的元素加 blocked-user 类。

TiebaCleaner 隐藏元素以后我还可以通过 Stylish 手动配其它样式上去。

**Comment by hanFengSan** [comment]
这个啊, 时间有点久远了,  我依稀记得贴吧有些元素的样式是直接写在style属性里面的, 有些还丧心病狂style里面!important的.....

blocked-user吗, 这个可以有, 我顺便加点transition这些吧_(:з」∠)_

**Comment by hanFengSan** [comment]
done, 详见另一个issue
