### ISSUE TITLE
Bug Report: 屏蔽用户失效

### ISSUE THREAD

**Issue by Cologler** [hanFengSan/TiebaCleaner#4]
版本：chrome store 1.5.0
测试链接：https://tieba.baidu.com/p/4766695709

![picpick-20170331-180052-001](https://cloud.githubusercontent.com/assets/10906962/24545994/09de36f6-163c-11e7-8989-6782fddc20a5.png)

**Comment by hanFengSan** [comment]
![2017-03-31 6 04 28](https://cloud.githubusercontent.com/assets/16065654/24546351/757250cc-163d-11e7-981f-a90b2c1dc8d6.png)

我这好像并没这个问题233.

你这个是屏蔽了前面7楼然后这个楼中楼并没有生效? 你那边是可以百分之百复现的吗? 如果不是, 那可能是事件调度上, 没有调度好. 如果是百分百复现, 那就有点头疼了.

**Comment by Cologler** [comment]
不断 F5 刷新，有时被屏蔽有时没用被屏蔽。

**Comment by hanFengSan** [comment]
了解, 应该是事件间的顺序没有很好的耦合, 晚上更新一波.

**Comment by hanFengSan** [comment]
测试的锅...我测试的时候都是ctrl+F5刷新, 不会出现这个问题.....这个问题只会在F5, 也就是有缓存的情况下会出现, 待我细看是哪出问题了orz

**Comment by hanFengSan** [comment]
v1.5.1里修复了, 原因是MutationObserver在某些情况下并没有绑定到帖子上, 从而导致无法检测变动, 楼中楼拉黑失效.
